### ISSUE TITLE
functionality checklist

### ISSUE THREAD

**Issue by danbjoseph** [AmericanRedCross/mbtiles-generate#1]
1. A map interface should let the user select an AOI and submit a request for mbtiles.
   - The server should generate mbtiles (see the [OpenMapKit wiki](https://github.com/AmericanRedCross/OpenMapKit/wiki/Creating-Your-Own-MBTiles-Basemap-File))
   - Metadata for each request should include: name (user provided), bbox, generation start time, generation end time, file size, file location
   - mbtiles files should be saved/moved to s3
2. A table interface should show all requests. Files that have not yet been completely generated and are not yet ready for download should be marked as such.
## basic
- [ ] user authentication
  - [ ] permission levels
    - user= approved, can request/download mbtiles
    - admin= can remove users, change user permissions, delete mbtiles
- [ ] leaflet map to create AOI bounding box and feed name, bbox to server
- [ ] generate mbtiles
- [ ] list requested mbtiles as well as status
- [ ] provide link to download mbtiles
- [ ] provide overpass query text
## advanced
- [ ] limit bounding box area (not for admin, only for user)
- [ ] map to show extents of generated mbtiles
- [ ] different tile servers?
